version: 2

sources:
  - name: jaffle_shop
    schema: raw
    tables:
      - name: customers
      - name: items
      - name: orders
      - name: products
      - name: stores
      - name: supplies
